# Generated by Django 4.2 on 2026-01-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('video_file', models.FileField(upload_to='movies/')),
                ('thumbnail', models.FileField(upload_to='thumbnails/')),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
